### ISSUE TITLE
[Bug] Время старта пакета не совпадает с временем старта 1-ого задания

### ISSUE THREAD

**Issue by vladpro3** [vladpro3/platform_adn-core#2]
Скорее всего необходимо присваивать время старта пакета к времени старта первого задания этого пакета, для того, чтобы они идеально совпадали. 
Время от времени разница составляет ~1с. Может влиять на общую статистику.

**Comment by vladpro3** [comment]
Влетит фикс минусового времени на клиенте, вместе с которым пропал данный баг.
Если время начала пакета и время первого задания приравниваются, можно закрывать

**Comment by Setoreon** [comment]
Синхронизировал
