### ISSUE TITLE
[Change] Убрать Required в модели таска

### ISSUE THREAD

**Issue by vladpro3** [vladpro3/platform_adn-core#3]
Мб принимать как "", если логин/пароль не был введен. Тогда не придется парится с нулевой длинной и копировать "логин в пароль" в задании sql-иньекции.

**Comment by vladpro3** [comment]
Также из-за этого зд (где на странице чекаю наличие переменных из вьюбага) можно пройти еще одним способом (изичный, если ты не тупой)
Т.к. после того, как отправляешь пустую форму - сервак возвращает страницу (пишет, что лог/пасс не введен), но не передает переменные из GET, тем самым страница не видит переменную для этого зд

**Comment by Setoreon** [comment]
Убрал
